title: Zinezilla
tagline: Comic, Zine, Illustration + Animation Festival
description: >-
  Zine fair organised by Mereida fajardo

owner:
  name: Danny Fajardo
  email: fajardodanny@yahoo.co.uk
  github: fajard01

tags:
  - GitHub
  - GitHub Pages
  - Zinezilla

locale: en_GB

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-timeago

livereload: true

sass:
  sass_dir: _sass
include:
  - _pages
  - _includes

